/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as authSignInImport } from './routes/(auth)/sign-in'
import { Route as authOtpImport } from './routes/(auth)/otp'
import { Route as auth500Import } from './routes/(auth)/500'

// Create Virtual Routes

const errors503LazyImport = createFileRoute('/(errors)/503')()
const errors500LazyImport = createFileRoute('/(errors)/500')()
const errors404LazyImport = createFileRoute('/(errors)/404')()
const errors403LazyImport = createFileRoute('/(errors)/403')()
const errors401LazyImport = createFileRoute('/(errors)/401')()
const authSignUpLazyImport = createFileRoute('/(auth)/sign-up')()
const authSignIn2LazyImport = createFileRoute('/(auth)/sign-in-2')()
const authForgotPasswordLazyImport = createFileRoute(
  '/(auth)/forgot-password',
)()
const AuthenticatedSettingsRouteLazyImport = createFileRoute(
  '/_authenticated/settings',
)()
const AuthenticatedRecordsRouteLazyImport = createFileRoute(
  '/_authenticated/records',
)()
const AuthenticatedLogsRouteLazyImport = createFileRoute(
  '/_authenticated/logs',
)()
const AuthenticatedAnalyticsRouteLazyImport = createFileRoute(
  '/_authenticated/analytics',
)()
const AuthenticatedUsersIndexLazyImport = createFileRoute(
  '/_authenticated/users/',
)()
const AuthenticatedTasksIndexLazyImport = createFileRoute(
  '/_authenticated/tasks/',
)()
const AuthenticatedSettingsIndexLazyImport = createFileRoute(
  '/_authenticated/settings/',
)()
const AuthenticatedProjectIndexLazyImport = createFileRoute(
  '/_authenticated/project/',
)()
const AuthenticatedNodeIndexLazyImport = createFileRoute(
  '/_authenticated/node/',
)()
const AuthenticatedMonacoIndexLazyImport = createFileRoute(
  '/_authenticated/monaco/',
)()
const AuthenticatedHelpCenterIndexLazyImport = createFileRoute(
  '/_authenticated/help-center/',
)()
const AuthenticatedChatsIndexLazyImport = createFileRoute(
  '/_authenticated/chats/',
)()
const AuthenticatedAppsIndexLazyImport = createFileRoute(
  '/_authenticated/apps/',
)()
const AuthenticatedSettingsSoftwareLazyImport = createFileRoute(
  '/_authenticated/settings/software',
)()
const AuthenticatedSettingsSensorLazyImport = createFileRoute(
  '/_authenticated/settings/sensor',
)()
const AuthenticatedSettingsRobotLazyImport = createFileRoute(
  '/_authenticated/settings/robot',
)()
const AuthenticatedSettingsPlcLazyImport = createFileRoute(
  '/_authenticated/settings/plc',
)()
const AuthenticatedSettingsDetectionLazyImport = createFileRoute(
  '/_authenticated/settings/detection',
)()
const AuthenticatedSettingsCameraLazyImport = createFileRoute(
  '/_authenticated/settings/camera',
)()

// Create/Update Routes

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const errors503LazyRoute = errors503LazyImport
  .update({
    id: '/(errors)/503',
    path: '/503',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/503.lazy').then((d) => d.Route))

const errors500LazyRoute = errors500LazyImport
  .update({
    id: '/(errors)/500',
    path: '/500',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/500.lazy').then((d) => d.Route))

const errors404LazyRoute = errors404LazyImport
  .update({
    id: '/(errors)/404',
    path: '/404',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/404.lazy').then((d) => d.Route))

const errors403LazyRoute = errors403LazyImport
  .update({
    id: '/(errors)/403',
    path: '/403',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/403.lazy').then((d) => d.Route))

const errors401LazyRoute = errors401LazyImport
  .update({
    id: '/(errors)/401',
    path: '/401',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/401.lazy').then((d) => d.Route))

const authSignUpLazyRoute = authSignUpLazyImport
  .update({
    id: '/(auth)/sign-up',
    path: '/sign-up',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-up.lazy').then((d) => d.Route))

const authSignIn2LazyRoute = authSignIn2LazyImport
  .update({
    id: '/(auth)/sign-in-2',
    path: '/sign-in-2',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-in-2.lazy').then((d) => d.Route))

const authForgotPasswordLazyRoute = authForgotPasswordLazyImport
  .update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/forgot-password.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsRouteLazyRoute =
  AuthenticatedSettingsRouteLazyImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/route.lazy').then((d) => d.Route),
  )

const AuthenticatedRecordsRouteLazyRoute =
  AuthenticatedRecordsRouteLazyImport.update({
    id: '/records',
    path: '/records',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/records/route.lazy').then((d) => d.Route),
  )

const AuthenticatedLogsRouteLazyRoute = AuthenticatedLogsRouteLazyImport.update(
  {
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
).lazy(() =>
  import('./routes/_authenticated/logs/route.lazy').then((d) => d.Route),
)

const AuthenticatedAnalyticsRouteLazyRoute =
  AuthenticatedAnalyticsRouteLazyImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/analytics/route.lazy').then((d) => d.Route),
  )

const authSignInRoute = authSignInImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const authOtpRoute = authOtpImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRoute,
} as any)

const auth500Route = auth500Import.update({
  id: '/(auth)/500',
  path: '/500',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedUsersIndexLazyRoute =
  AuthenticatedUsersIndexLazyImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/users/index.lazy').then((d) => d.Route),
  )

const AuthenticatedTasksIndexLazyRoute =
  AuthenticatedTasksIndexLazyImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/tasks/index.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsIndexLazyRoute =
  AuthenticatedSettingsIndexLazyImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/index.lazy').then((d) => d.Route),
  )

const AuthenticatedProjectIndexLazyRoute =
  AuthenticatedProjectIndexLazyImport.update({
    id: '/project/',
    path: '/project/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/project/index.lazy').then((d) => d.Route),
  )

const AuthenticatedNodeIndexLazyRoute = AuthenticatedNodeIndexLazyImport.update(
  {
    id: '/node/',
    path: '/node/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
).lazy(() =>
  import('./routes/_authenticated/node/index.lazy').then((d) => d.Route),
)

const AuthenticatedMonacoIndexLazyRoute =
  AuthenticatedMonacoIndexLazyImport.update({
    id: '/monaco/',
    path: '/monaco/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/monaco/index.lazy').then((d) => d.Route),
  )

const AuthenticatedHelpCenterIndexLazyRoute =
  AuthenticatedHelpCenterIndexLazyImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/help-center/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedChatsIndexLazyRoute =
  AuthenticatedChatsIndexLazyImport.update({
    id: '/chats/',
    path: '/chats/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/chats/index.lazy').then((d) => d.Route),
  )

const AuthenticatedAppsIndexLazyRoute = AuthenticatedAppsIndexLazyImport.update(
  {
    id: '/apps/',
    path: '/apps/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
).lazy(() =>
  import('./routes/_authenticated/apps/index.lazy').then((d) => d.Route),
)

const AuthenticatedSettingsSoftwareLazyRoute =
  AuthenticatedSettingsSoftwareLazyImport.update({
    id: '/software',
    path: '/software',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/software.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsSensorLazyRoute =
  AuthenticatedSettingsSensorLazyImport.update({
    id: '/sensor',
    path: '/sensor',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/sensor.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsRobotLazyRoute =
  AuthenticatedSettingsRobotLazyImport.update({
    id: '/robot',
    path: '/robot',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/robot.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsPlcLazyRoute =
  AuthenticatedSettingsPlcLazyImport.update({
    id: '/plc',
    path: '/plc',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/plc.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsDetectionLazyRoute =
  AuthenticatedSettingsDetectionLazyImport.update({
    id: '/detection',
    path: '/detection',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/detection.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsCameraLazyRoute =
  AuthenticatedSettingsCameraLazyImport.update({
    id: '/camera',
    path: '/camera',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/camera.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/500': {
      id: '/(auth)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof auth500Import
      parentRoute: typeof rootRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/records': {
      id: '/_authenticated/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AuthenticatedRecordsRouteLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2LazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpLazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503LazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/camera': {
      id: '/_authenticated/settings/camera'
      path: '/camera'
      fullPath: '/settings/camera'
      preLoaderRoute: typeof AuthenticatedSettingsCameraLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/detection': {
      id: '/_authenticated/settings/detection'
      path: '/detection'
      fullPath: '/settings/detection'
      preLoaderRoute: typeof AuthenticatedSettingsDetectionLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/plc': {
      id: '/_authenticated/settings/plc'
      path: '/plc'
      fullPath: '/settings/plc'
      preLoaderRoute: typeof AuthenticatedSettingsPlcLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/robot': {
      id: '/_authenticated/settings/robot'
      path: '/robot'
      fullPath: '/settings/robot'
      preLoaderRoute: typeof AuthenticatedSettingsRobotLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/sensor': {
      id: '/_authenticated/settings/sensor'
      path: '/sensor'
      fullPath: '/settings/sensor'
      preLoaderRoute: typeof AuthenticatedSettingsSensorLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/software': {
      id: '/_authenticated/settings/software'
      path: '/software'
      fullPath: '/settings/software'
      preLoaderRoute: typeof AuthenticatedSettingsSoftwareLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/monaco/': {
      id: '/_authenticated/monaco/'
      path: '/monaco'
      fullPath: '/monaco'
      preLoaderRoute: typeof AuthenticatedMonacoIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/node/': {
      id: '/_authenticated/node/'
      path: '/node'
      fullPath: '/node'
      preLoaderRoute: typeof AuthenticatedNodeIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/project/': {
      id: '/_authenticated/project/'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof AuthenticatedProjectIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedSettingsRouteLazyRouteChildren {
  AuthenticatedSettingsCameraLazyRoute: typeof AuthenticatedSettingsCameraLazyRoute
  AuthenticatedSettingsDetectionLazyRoute: typeof AuthenticatedSettingsDetectionLazyRoute
  AuthenticatedSettingsPlcLazyRoute: typeof AuthenticatedSettingsPlcLazyRoute
  AuthenticatedSettingsRobotLazyRoute: typeof AuthenticatedSettingsRobotLazyRoute
  AuthenticatedSettingsSensorLazyRoute: typeof AuthenticatedSettingsSensorLazyRoute
  AuthenticatedSettingsSoftwareLazyRoute: typeof AuthenticatedSettingsSoftwareLazyRoute
  AuthenticatedSettingsIndexLazyRoute: typeof AuthenticatedSettingsIndexLazyRoute
}

const AuthenticatedSettingsRouteLazyRouteChildren: AuthenticatedSettingsRouteLazyRouteChildren =
  {
    AuthenticatedSettingsCameraLazyRoute: AuthenticatedSettingsCameraLazyRoute,
    AuthenticatedSettingsDetectionLazyRoute:
      AuthenticatedSettingsDetectionLazyRoute,
    AuthenticatedSettingsPlcLazyRoute: AuthenticatedSettingsPlcLazyRoute,
    AuthenticatedSettingsRobotLazyRoute: AuthenticatedSettingsRobotLazyRoute,
    AuthenticatedSettingsSensorLazyRoute: AuthenticatedSettingsSensorLazyRoute,
    AuthenticatedSettingsSoftwareLazyRoute:
      AuthenticatedSettingsSoftwareLazyRoute,
    AuthenticatedSettingsIndexLazyRoute: AuthenticatedSettingsIndexLazyRoute,
  }

const AuthenticatedSettingsRouteLazyRouteWithChildren =
  AuthenticatedSettingsRouteLazyRoute._addFileChildren(
    AuthenticatedSettingsRouteLazyRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRouteLazyRoute: typeof AuthenticatedAnalyticsRouteLazyRoute
  AuthenticatedLogsRouteLazyRoute: typeof AuthenticatedLogsRouteLazyRoute
  AuthenticatedRecordsRouteLazyRoute: typeof AuthenticatedRecordsRouteLazyRoute
  AuthenticatedSettingsRouteLazyRoute: typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAppsIndexLazyRoute: typeof AuthenticatedAppsIndexLazyRoute
  AuthenticatedChatsIndexLazyRoute: typeof AuthenticatedChatsIndexLazyRoute
  AuthenticatedHelpCenterIndexLazyRoute: typeof AuthenticatedHelpCenterIndexLazyRoute
  AuthenticatedMonacoIndexLazyRoute: typeof AuthenticatedMonacoIndexLazyRoute
  AuthenticatedNodeIndexLazyRoute: typeof AuthenticatedNodeIndexLazyRoute
  AuthenticatedProjectIndexLazyRoute: typeof AuthenticatedProjectIndexLazyRoute
  AuthenticatedTasksIndexLazyRoute: typeof AuthenticatedTasksIndexLazyRoute
  AuthenticatedUsersIndexLazyRoute: typeof AuthenticatedUsersIndexLazyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRouteLazyRoute: AuthenticatedAnalyticsRouteLazyRoute,
  AuthenticatedLogsRouteLazyRoute: AuthenticatedLogsRouteLazyRoute,
  AuthenticatedRecordsRouteLazyRoute: AuthenticatedRecordsRouteLazyRoute,
  AuthenticatedSettingsRouteLazyRoute:
    AuthenticatedSettingsRouteLazyRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAppsIndexLazyRoute: AuthenticatedAppsIndexLazyRoute,
  AuthenticatedChatsIndexLazyRoute: AuthenticatedChatsIndexLazyRoute,
  AuthenticatedHelpCenterIndexLazyRoute: AuthenticatedHelpCenterIndexLazyRoute,
  AuthenticatedMonacoIndexLazyRoute: AuthenticatedMonacoIndexLazyRoute,
  AuthenticatedNodeIndexLazyRoute: AuthenticatedNodeIndexLazyRoute,
  AuthenticatedProjectIndexLazyRoute: AuthenticatedProjectIndexLazyRoute,
  AuthenticatedTasksIndexLazyRoute: AuthenticatedTasksIndexLazyRoute,
  AuthenticatedUsersIndexLazyRoute: AuthenticatedUsersIndexLazyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/500': typeof errors500LazyRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/analytics': typeof AuthenticatedAnalyticsRouteLazyRoute
  '/logs': typeof AuthenticatedLogsRouteLazyRoute
  '/records': typeof AuthenticatedRecordsRouteLazyRoute
  '/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/503': typeof errors503LazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/settings/camera': typeof AuthenticatedSettingsCameraLazyRoute
  '/settings/detection': typeof AuthenticatedSettingsDetectionLazyRoute
  '/settings/plc': typeof AuthenticatedSettingsPlcLazyRoute
  '/settings/robot': typeof AuthenticatedSettingsRobotLazyRoute
  '/settings/sensor': typeof AuthenticatedSettingsSensorLazyRoute
  '/settings/software': typeof AuthenticatedSettingsSoftwareLazyRoute
  '/apps': typeof AuthenticatedAppsIndexLazyRoute
  '/chats': typeof AuthenticatedChatsIndexLazyRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexLazyRoute
  '/monaco': typeof AuthenticatedMonacoIndexLazyRoute
  '/node': typeof AuthenticatedNodeIndexLazyRoute
  '/project': typeof AuthenticatedProjectIndexLazyRoute
  '/settings/': typeof AuthenticatedSettingsIndexLazyRoute
  '/tasks': typeof AuthenticatedTasksIndexLazyRoute
  '/users': typeof AuthenticatedUsersIndexLazyRoute
}

export interface FileRoutesByTo {
  '/500': typeof errors500LazyRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/analytics': typeof AuthenticatedAnalyticsRouteLazyRoute
  '/logs': typeof AuthenticatedLogsRouteLazyRoute
  '/records': typeof AuthenticatedRecordsRouteLazyRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/503': typeof errors503LazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/settings/camera': typeof AuthenticatedSettingsCameraLazyRoute
  '/settings/detection': typeof AuthenticatedSettingsDetectionLazyRoute
  '/settings/plc': typeof AuthenticatedSettingsPlcLazyRoute
  '/settings/robot': typeof AuthenticatedSettingsRobotLazyRoute
  '/settings/sensor': typeof AuthenticatedSettingsSensorLazyRoute
  '/settings/software': typeof AuthenticatedSettingsSoftwareLazyRoute
  '/apps': typeof AuthenticatedAppsIndexLazyRoute
  '/chats': typeof AuthenticatedChatsIndexLazyRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexLazyRoute
  '/monaco': typeof AuthenticatedMonacoIndexLazyRoute
  '/node': typeof AuthenticatedNodeIndexLazyRoute
  '/project': typeof AuthenticatedProjectIndexLazyRoute
  '/settings': typeof AuthenticatedSettingsIndexLazyRoute
  '/tasks': typeof AuthenticatedTasksIndexLazyRoute
  '/users': typeof AuthenticatedUsersIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/500': typeof auth500Route
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRouteLazyRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRouteLazyRoute
  '/_authenticated/records': typeof AuthenticatedRecordsRouteLazyRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordLazyRoute
  '/(auth)/sign-in-2': typeof authSignIn2LazyRoute
  '/(auth)/sign-up': typeof authSignUpLazyRoute
  '/(errors)/401': typeof errors401LazyRoute
  '/(errors)/403': typeof errors403LazyRoute
  '/(errors)/404': typeof errors404LazyRoute
  '/(errors)/500': typeof errors500LazyRoute
  '/(errors)/503': typeof errors503LazyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/settings/camera': typeof AuthenticatedSettingsCameraLazyRoute
  '/_authenticated/settings/detection': typeof AuthenticatedSettingsDetectionLazyRoute
  '/_authenticated/settings/plc': typeof AuthenticatedSettingsPlcLazyRoute
  '/_authenticated/settings/robot': typeof AuthenticatedSettingsRobotLazyRoute
  '/_authenticated/settings/sensor': typeof AuthenticatedSettingsSensorLazyRoute
  '/_authenticated/settings/software': typeof AuthenticatedSettingsSoftwareLazyRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexLazyRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexLazyRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexLazyRoute
  '/_authenticated/monaco/': typeof AuthenticatedMonacoIndexLazyRoute
  '/_authenticated/node/': typeof AuthenticatedNodeIndexLazyRoute
  '/_authenticated/project/': typeof AuthenticatedProjectIndexLazyRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexLazyRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexLazyRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/500'
    | '/otp'
    | '/sign-in'
    | '/analytics'
    | '/logs'
    | '/records'
    | '/settings'
    | '/forgot-password'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/'
    | '/settings/camera'
    | '/settings/detection'
    | '/settings/plc'
    | '/settings/robot'
    | '/settings/sensor'
    | '/settings/software'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/monaco'
    | '/node'
    | '/project'
    | '/settings/'
    | '/tasks'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/500'
    | '/otp'
    | '/sign-in'
    | '/analytics'
    | '/logs'
    | '/records'
    | '/forgot-password'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/'
    | '/settings/camera'
    | '/settings/detection'
    | '/settings/plc'
    | '/settings/robot'
    | '/settings/sensor'
    | '/settings/software'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/monaco'
    | '/node'
    | '/project'
    | '/settings'
    | '/tasks'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/500'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/_authenticated/analytics'
    | '/_authenticated/logs'
    | '/_authenticated/records'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/settings/camera'
    | '/_authenticated/settings/detection'
    | '/_authenticated/settings/plc'
    | '/_authenticated/settings/robot'
    | '/_authenticated/settings/sensor'
    | '/_authenticated/settings/software'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/monaco/'
    | '/_authenticated/node/'
    | '/_authenticated/project/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  auth500Route: typeof auth500Route
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authForgotPasswordLazyRoute: typeof authForgotPasswordLazyRoute
  authSignIn2LazyRoute: typeof authSignIn2LazyRoute
  authSignUpLazyRoute: typeof authSignUpLazyRoute
  errors401LazyRoute: typeof errors401LazyRoute
  errors403LazyRoute: typeof errors403LazyRoute
  errors404LazyRoute: typeof errors404LazyRoute
  errors500LazyRoute: typeof errors500LazyRoute
  errors503LazyRoute: typeof errors503LazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  auth500Route: auth500Route,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authForgotPasswordLazyRoute: authForgotPasswordLazyRoute,
  authSignIn2LazyRoute: authSignIn2LazyRoute,
  authSignUpLazyRoute: authSignUpLazyRoute,
  errors401LazyRoute: errors401LazyRoute,
  errors403LazyRoute: errors403LazyRoute,
  errors404LazyRoute: errors404LazyRoute,
  errors500LazyRoute: errors500LazyRoute,
  errors503LazyRoute: errors503LazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/(auth)/500",
        "/(auth)/otp",
        "/(auth)/sign-in",
        "/(auth)/forgot-password",
        "/(auth)/sign-in-2",
        "/(auth)/sign-up",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/(errors)/503"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/analytics",
        "/_authenticated/logs",
        "/_authenticated/records",
        "/_authenticated/settings",
        "/_authenticated/",
        "/_authenticated/apps/",
        "/_authenticated/chats/",
        "/_authenticated/help-center/",
        "/_authenticated/monaco/",
        "/_authenticated/node/",
        "/_authenticated/project/",
        "/_authenticated/tasks/",
        "/_authenticated/users/"
      ]
    },
    "/(auth)/500": {
      "filePath": "(auth)/500.tsx"
    },
    "/(auth)/otp": {
      "filePath": "(auth)/otp.tsx"
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx"
    },
    "/_authenticated/analytics": {
      "filePath": "_authenticated/analytics/route.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/logs": {
      "filePath": "_authenticated/logs/route.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/records": {
      "filePath": "_authenticated/records/route.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings": {
      "filePath": "_authenticated/settings/route.lazy.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/camera",
        "/_authenticated/settings/detection",
        "/_authenticated/settings/plc",
        "/_authenticated/settings/robot",
        "/_authenticated/settings/sensor",
        "/_authenticated/settings/software",
        "/_authenticated/settings/"
      ]
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.lazy.tsx"
    },
    "/(auth)/sign-in-2": {
      "filePath": "(auth)/sign-in-2.lazy.tsx"
    },
    "/(auth)/sign-up": {
      "filePath": "(auth)/sign-up.lazy.tsx"
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.lazy.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.lazy.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.lazy.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.lazy.tsx"
    },
    "/(errors)/503": {
      "filePath": "(errors)/503.lazy.tsx"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/camera": {
      "filePath": "_authenticated/settings/camera.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/detection": {
      "filePath": "_authenticated/settings/detection.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/plc": {
      "filePath": "_authenticated/settings/plc.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/robot": {
      "filePath": "_authenticated/settings/robot.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/sensor": {
      "filePath": "_authenticated/settings/sensor.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/software": {
      "filePath": "_authenticated/settings/software.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/apps/": {
      "filePath": "_authenticated/apps/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/chats/": {
      "filePath": "_authenticated/chats/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/help-center/": {
      "filePath": "_authenticated/help-center/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/monaco/": {
      "filePath": "_authenticated/monaco/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/node/": {
      "filePath": "_authenticated/node/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/project/": {
      "filePath": "_authenticated/project/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/": {
      "filePath": "_authenticated/settings/index.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/tasks/": {
      "filePath": "_authenticated/tasks/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/users/": {
      "filePath": "_authenticated/users/index.lazy.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
