# 硬件连接设置和参数设置

[sensors]
ip = '192.168.0.101'



[cameras]
ip = '192.168.1.100'
lib_path = 'C:\\Program Files (x86)\\Common Files\\MVS\\Runtime\\Win64_x64\\MvCameraControl.dll'

 
[robot]
ip_port = '172.16.1.30:502'


[plc]
ip_port = '192.168.1.88:3100'
