# 硬件连接设置和参数设置

[sensors]
ip = ''



[cameras]
ip = '192.168.1.100'
lib_path = 'C:\\Program Files (x86)\\Common Files\\MVS\\Runtime\\Win64_x64\\MvCameraControl.dll'


[robot]
ip = ''


[plc]
ip_port = '192.168.1.88:502'
