# 型号检测配置

[type]
all_type = ['EH09','EH12','EY28','EK30','EK40']
current_type = 'EH09'

[type.EH09]
run_sequence = ['A','B','C','D','E']

[type.EH09.A]
run_sequence = [1,2]
[type.EH09.A.1]
thru_home = false
screw_hole = 'M8'
diameter_min = 0
diameter_max = 0
depth_min = 0
depth_max = 0

[type.EH09.A.2]
thru_home = false
screw_hole = 'M8'
diameter_min = 0
diameter_max = 0
depth_min = 0
depth_max = 0























[type.EH12]
run_sequence = ['A','B','C','D','E']




[type.EY28]
run_sequence = ['A','B','C','D','E']

[type.EK30]
run_sequence = ['A','B','C','D','E']

[type.EK40]
run_sequence = ['A','B','C','D','E']