# 运行时设置
[log]
log_dir = ''


[service]
database = 'surreal'
algo_backend = 'fastapi'

[database]
database = 'surreal'
ip_port = '127.0.0.1:8000'

[save]
orginal_image_save = true



[run]
enable_stop = false
enable_diameter = false
enable_depth = false
enable_detect = true


[result]